Home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home),
    path('about/', views.about),
    path('announcement/', views.announcement),
    path('announcement/<str:id>', views.announcementDetail),
    path('about/team/', views.team),
    path('about/faq/', views.faq),
    path('about/support/', views.support),
]

Profile/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('detail/<username>/', views.profileView),
    path('change', views.profileChangeView),
    path('claimrank', views.claimRankView),
    
    path('notification', views.profileNotification),
    path('notification/delete', views.profileNotificationDelete),
    path('my', views.redirectProfileView),
    path('search/', views.searchView),
    path('topusers/', views.topUserListView),
    path('setting', views.setting),
]

Profile/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    about = models.TextField(default='người dùng không chia sẻ thông tin')
    roles = [
        ('S', 'Học sinh'),
        ('T', 'Giáo viên'),
        ('A', 'admin')
    ]
    ranks = [
        ('A', 'Vàng'),
        ('B', 'Bạc'),
        ('C', 'Đồng'),
        ('U', 'Chưa xếp hạng'),
    ]
    role = models.CharField(max_length=1 ,choices=roles, default='S')
    rank = models.CharField(max_length=1 ,choices=ranks, default='U')
    NumberOfPosts = models.IntegerField(default=0)
    NumberOfGoodPosts = models.IntegerField(default=0, help_text='tăng giá trị nếu bài viết của người dùng là tự viết')
    points = models.IntegerField(default=0, help_text='Điểm | dựa trên số bài viết đã đăng')
    chatGPTLimit = models.IntegerField(default=0, help_text='Giới hạn sử dụng ChatGPT API')
    createdAt = models.DateTimeField(auto_now_add=True)

class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    content = models.TextField()
    link = models.CharField(blank=True, max_length=255)
    createdAt = models.DateTimeField(auto_now_add=True)

Profile/forms.py
from django import forms
import re
from django.contrib.auth.models import User as user
from Others.func import getBadwords
bad_words = getBadwords()

class ChangeProfileForm(forms.Form):
    firstname = forms.CharField(label='Tên', max_length = 30)
    lastname = forms.CharField(label='Họ', max_length = 50)
    about = forms.CharField(label="About", widget=forms.Textarea)

    def clean_firstname(self):
        first_name = self.cleaned_data['firstname'].upper()
        first_name = first_name.replace('  ', ' ')
        for word in bad_words:
            if first_name.find(str(word).upper()) != -1:
                raise forms.ValidationError("Tên của bạn chứa từ ngữ không phù hợp")
                
        if not (re.search(r'^[AÁÀẢÃẠaáàảãạĂẮẰẲẴẶăắằẳẵạÂẤẦẨẪẬâấầẩẫậBbCcDdĐđEÉÈẺẼẸeéèẽẻẹÊẾỀỂỄỆêếềểễệGgHhIÍÌỈĨỊiíìỉĩịKkLlMmNnOÓÒỎÕỌoóòỏõọÔỐỒỔÕỌoóòỏõọƠỚỜỞỠỢơớờởỡợPpQqRrSsTtUÚỦŨỤuúùủũụƯỨỪỬỮỰưứừửữựVvXxYyZz ]+$', first_name)):
            raise forms.ValidationError("Tên của bạn không thể chứa các kí tự ngoài chữ hoa và chữ thường")
        if first_name.isspace() or first_name == '':
            raise forms.ValidationError("Tên của bạn không hợp lệ!")
        return self.cleaned_data['firstname']

    def clean_lastname(self):
        last_name = self.cleaned_data['lastname'].upper()
        last_name = last_name.replace('  ', ' ')
        for word in bad_words:
            if last_name.find(str(word).upper()) != -1:
                raise forms.ValidationError("Họ của bạn chứa từ ngữ không phù hợp")
        if not (re.search(r'^[AÁÀẢÃẠaáàảãạĂẮẰẲẴẶăắằẳẵạÂẤẦẨẪẬâấầẩẫậBbCcDdĐđEÉÈẺẼẸeéèẽẻẹÊẾỀỂỄỆêếềểễệGgHhIÍÌỈĨỊiíìỉĩịKkLlMmNnOÓÒỎÕỌoóòỏõọÔỐỒỔÕỌoóòỏõọƠỚỜỞỠỢơớờởỡợPpQqRrSsTtUÚỦŨỤuúùủũụƯỨỪỬỮỰưứừửữựVvXxYyZz ]+$', last_name)):
            raise forms.ValidationError("Họ của bạn không thể chứa các kí tự ngoài chữ hoa và chữ thường")
        if last_name == '':
            raise forms.ValidationError("Họ của bạn không hợp lệ!")    
        return self.cleaned_data['lastname']

    def clean_about(self):
        about = self.cleaned_data['about'].lower()
        for word in bad_words:
            if about.find(str(word)) != -1:
                raise forms.ValidationError("About của bạn chứa từ ngữ không phù hợp")
        return self.cleaned_data['about']

Profile/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from django.contrib.auth.models import User
from .models import Profile as profile
from .models import Notification as Notification
from .forms import ChangeProfileForm
from .func import is_own_page, update_top_users
from Posts.models import Post as post, Test as test
from question.models import Question

from Posts.func import get_newest_posts, get_newest_tests, markdown_to_html
from Others.func import get_website_info

def profileView(request, username):
    data = get_website_info()
    user = User.objects.get(username=username)
    ChangeNumberOfPosts_User = profile.objects.get(user=user)
    ChangeNumberOfPosts_User.NumberOfPosts = post.objects.filter(author=user, is_publish=True).values().count() + test.objects.filter(author=user, is_publish=True).values().count()
    ChangeNumberOfPosts_User.NumberOfGoodPosts = post.objects.filter(author=user, is_publish=True, is_good_post=True).values().count() + test.objects.filter(author=user, is_publish=True, is_good_test=True).values().count()
    ChangeNumberOfPosts_User.points = (ChangeNumberOfPosts_User.NumberOfGoodPosts)*2 + (ChangeNumberOfPosts_User.NumberOfPosts - ChangeNumberOfPosts_User.NumberOfGoodPosts)
    ChangeNumberOfPosts_User.save()

    posts = post.objects.filter(is_publish=True, author=user).order_by('-createdAt')[:10]
    tests = test.objects.filter(is_publish=True, author=user).order_by('-createdAt')[:10]

    data['User'] = profile.objects.get(user=user)
    data['is_own_profile'] = str(request.user.username) == str(user.username)
    data['posts'] = posts
    data['tests'] = tests
    data['questions'] = Question.objects.filter(is_published=True, author=user).order_by("-is_open")[:10]

    return render(request, 'profile/Profile.html', data)

@login_required(login_url='/login')
def profileChangeView(request):
    data = get_website_info()
    user = request.user
    userProfile = profile.objects.get(user=user)

    form = ChangeProfileForm()
    if request.method == 'POST':
        form = ChangeProfileForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['firstname']
            last_name = form.cleaned_data['lastname']
            user.first_name = first_name
            user.last_name = last_name
            user.save()
            userProfile.name = last_name + " " + first_name
            userProfile.about = form.cleaned_data['about']
            userProfile.save()
            return HttpResponseRedirect(f'/profile/detail/{user.username}')


    form.fields['firstname'].initial = user.first_name
    form.fields['lastname'].initial = user.last_name
    form.fields['about'].initial = userProfile.about

    data['form'] = form
    return render(request, 'profile/ProfileChange.html', data)

@login_required(login_url='/login')
def profileNotification(request):
    data = get_website_info()
    user = User.objects.get(username=request.user)
    notifications = Notification.objects.filter(user = user).order_by('-createdAt')

    paginator = Paginator(notifications, 30)
    try:
        page_number = request.GET['page']
    except:
        page_number = 1
    page_obj = paginator.get_page(page_number)
    data['notifications'] = page_obj
    return render(request, 'profile/Notification.html', data)

@login_required(login_url='/login')
def profileNotificationDelete(request):
    id = request.GET.get('id')
    if (id == None):
        return HttpResponseRedirect(f'/profile/detail/{request.user.username}')
    noti = Notification.objects.filter(id=id)
    if (len(noti) != 1):
        return HttpResponseRedirect(f'/profile/notification')
    noti = noti[0]
    if (noti.user != request.user):
        return HttpResponseRedirect(f'/profile/detail/{request.user.username}')

    noti.delete()

    return HttpRespfonseRedirect(f'/profile/notification')

@login_required(login_url='/login')
def claimRankView(request):
    data = get_website_info()
    user = request.user
    userProfile = profile.objects.get(user=user)
    userProfile.NumberOfPosts = post.objects.filter(author=user, is_publish=True).values().count() + test.objects.filter(author=user, is_publish=True).values().count()
    userProfile.NumberOfGoodPosts = post.objects.filter(author=user, is_publish=True, is_good_post=True).values().count() + test.objects.filter(author=user, is_publish=True, is_good_test=True).values().count()
    userProfile.points = (userProfile.NumberOfGoodPosts)*2 + (userProfile.NumberOfPosts - userProfile.NumberOfGoodPosts)
    userProfile.save()
    userProfile = profile.objects.get(user=user)

    result = ''
    isClaimed = False
    if request.method == 'POST':
        if (10 <= userProfile.points) and (userProfile.points < 50) and (userProfile.rank != 'C'):
            userProfile.rank = 'C'
            result = 'Bạn đã nhận được hạng <i class="fas fa-medal" style="color: #cd7f32"></i> <b>Đồng</b>!'
        elif (50 <= userProfile.points) and (userProfile.points < 200) and (userProfile.rank != 'B'):
            userProfile.rank = 'B'
            result = 'Bạn đã nhận được hạng <i class="fas fa-medal" style="color: silver"></i> <b>Bạc</b>!'
        elif (200 <= userProfile.points) and (userProfile.rank != 'A'):
            userProfile.rank = 'A'
            result = 'Bạn đã nhận được hạng <i class="fas fa-medal" style="color: gold"></i> <b>Vàng</b>!'
        else:
            result = 'Có vẻ bạn chưa nhận được hạng mới!'
        userProfile.save()
        isClaimed = True
    data['isClaimed'] = isClaimed
    data['rank'] = result
    return render(request, 'profile/claimRank.html', data)

@login_required(login_url='/login')
def redirectProfileView(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(f"/profile/detail/{request.user}")
    else:
        return HttpResponseRedirect('/login')

def searchView(request):
    data = get_website_info()
    try:
        SearchData = {
            "is_searching": True,
            "usersFound": User.objects.filter(username__icontains=request.GET['username'])
        }
    except:
        SearchData = {
            "is_searching": False,
        }
    data.update(SearchData)
    return render(request, 'profile/SearchProfile.html', data)

@login_required(login_url='/login')
def topUserListView(request):
    data = get_website_info()
    #update NumberOfPost for all users
    update_top_users()

    #pagination
    valid_users = profile.objects.filter(NumberOfPosts__gt=0).order_by('-NumberOfPosts')
    paginator = Paginator(valid_users, 30)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    data['topUsers'] = page_obj
    return render(request, 'profile/topUsers.html', data)

@login_required(login_url='/login')
def setting(request):
    data = get_website_info()
    # discorduser = DiscordUser.objects.get(email=request.user.email)
    # data['Discord_Notification'] = discorduser.toggle_notifcation

    # discord_notification = request.POST.get('Discord_notification', None)
    # if (discord_notification != None):
    #     discorduser.toggle_notifcation = not data['Discord_Notification']
    #     discorduser.save()
    #     data['Discord_Notification'] = not data['Discord_Notification']

    return render(request, 'profile/setting.html', data)

Profile/templates/profile/Notification.html
{% extends "base.html" %}

{% block title %}Thông Báo{% endblock %}
{% block content %}
<h3><i class="fas fa-bell"></i> Thông báo của bạn</h3>

<div class="card">
    <div class="card-header">
      <h5 class="card-title">Danh sách thông báo</h5>
    </div>
    <div class="card-body">
      {% for noti in notifications %}
      <div class="card mb-2">
        <div class="card-body">
            <h6 class="card-title">{{ noti.title }}</h6>
            <p class="card-text">{{ noti.content }}</p>
            <p class="card-text"><small class="text-muted">{{ noti.createdAt|date:"G\:i d/m/Y" }}</small></p>
            {% if noti.link %}
                <a href="{{ noti.link }}" target="_blank" class="btn btn-primary">Xem thêm</a>
            {% endif %}
            <a href="/profile/notification/delete?id={{noti.id}}" class="btn btn-danger">xóa</a>
        </div>        
      </div>
      {% empty %}
      <p>Không có thông báo</p>
      {% endfor %}
    </div>
  </div>  
<div class="mt-3">
  <!-- pagination  -->
  {% if notifications.has_other_pages %}
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {% if notifications.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ notifications.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Trang Trước</span>
          </a>
        </li>
      {% endif %}
      {% for i in notifications.paginator.page_range %}
        {% if notifications.number == i %}
          <li class="page-item active"><a class="page-link" href="#">{{ i }} <span class="sr-only">(hiện tại)</span></a></li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}
      {% if notifications.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ notifications.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Trang Tiếp</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
  {% endif %}
</div>
{% endblock %}

Profile/templates/profile/Profile.html
{% extends "base.html" %}

{% block title %}{{ User.name }}{% endblock %}
{% block nav-profile-drop %}active{% endblock %}
{% block nav-myprofile-user %}active{% endblock %}

{% block content %}
<h3 class="mb-3 mt-3">
    <i class="fas fa-user"></i> Thông tin của {{User.name}}
    {% if User.rank == 'A' %}
    <i class="fas fa-medal" style="color: gold"></i>
    {% elif User.rank == 'B' %}
    <i class="fas fa-medal" style="color: silver"></i>
    {% elif User.rank == 'C' %}
    <i class="fas fa-medal" style="color: #cd7f32"></i>
    {% endif %}
</h3>

<div class="card mb-3">
  <div class="card-header">
    Thông tin cá nhân
  </div>
  <div class="card-body">
    <h5 class="card-title">{{User.name}}</h5>
    <p class="card-text"><i class="fas fa-user"></i> Tên tài khoản: {{User.user}}</p>
    <p class="card-text"><i class="fas fa-user-tag"></i> Vai trò: {{User.get_role_display}}</p>
    <p class="card-text">
      {% if User.rank == 'A' %}
      <i class="fas fa-medal" style="color: gold"></i>
      {% elif User.rank == 'B' %}
      <i class="fas fa-medal" style="color: silver"></i>
      {% elif User.rank == 'C' %}
      <i class="fas fa-medal" style="color: #cd7f32"></i>
      {% else %}
      <i class="fas fa-medal"></i>
      {% endif %}
      Hạng: {{User.get_rank_display}}
    </p>
    <p class="card-text"><i class="fas fa-clock"></i> Ngày tạo tài khoản: {{User.createdAt|date:"d/m/Y"}}</p>
    <p class="card-text"><i class="fas fa-clipboard"></i> Số bài viết đã đăng: {{User.NumberOfPosts}}</p>
    <p class="card-text"><i class="fas fa-circle"></i> Điểm: {{User.points}}</p>
    <h5 class="card-title">Giới thiệu</h5>
    <p class="card-text">{{User.about|linebreaks}}</p>
  </div>
</div>

<h4><i class="fas fa-book"></i> Bài học tập đã đăng</h4>
<div class="row">
    {% for post in posts %}
    <div class="col-md-4">
      <div class="card mt-3">
        <div class="card-body">
          <h5 class="card-title"><a href="/p/hoc_tap/p/{{ post.post_id }}">{{ post.title }}</a></h5>
          <h6 class="card-subtitle text-muted"><i class="fas fa-tag"></i> Tags:
            {% for key, value in post.tags.items %}
            <a href="/p/hoc_tap/tag/{{ key }}">{{ value }}</a>
            {% if not forloop.last %}, {% endif %}
            {% empty %}
            không có tag
            {% endfor %}
          </h6>
        </div>
        <div class="card-footer text-muted border-top-0">
            <p class="m-0"><i class="fas fa-user"></i> <a href="/profile/detail/{{post.author}}">{{post.author}}</a></p>
            <p class="m-0"><i class="fas fa-calendar-alt"></i> {{post.createdAt|date:"d/m/Y"}}</p>
        </div>
      </div>
    </div>
    {% empty %}
    <p><i>Người dùng chưa đăng.</i></p>
    {% endfor %}
  </div>
<h4><i class="fas fa-book mt-4"></i> Bài kiểm tra đã đăng</h4>
  <div class="row">
    {% for post in tests %}
    <div class="col-md-4">
      <div class="card mt-3">
        <div class="card-body">
          <h5 class="card-title"><a href="/p/kiem_tra/p/{{ post.test_id }}">{{ post.title }}</a></h5>
          <h6 class="card-subtitle text-muted"><i class="fas fa-tag"></i> Tags:
            {% for key, value in post.tags.items %}
            <a href="/p/hoc_tap/tag/{{ key }}">{{ value }}</a>
            {% if not forloop.last %}, {% endif %}
            {% empty %}
            không có tag
            {% endfor %}
          </h6>
        </div>
        <div class="card-footer text-muted border-top-0">
          <p class="m-0"><i class="fas fa-user"></i> <a href="/profile/detail/{{post.author}}">{{post.author}}</a></p>
          <p class="m-0"><i class="fas fa-calendar-alt"></i> {{post.createdAt|date:"d/m/Y"}}</p>
        </div>
      </div>
    </div>
    {% empty %}
    <p><i>Người dùng chưa đăng.</i></p>
    {% endfor %}
  </div>

  <h4 class="mt-3"><i class="fas fa-comments"></i> Hỏi Đáp</h4>
  <div class="row">
    {% for post in questions %}
    <div class="col-md-4">
      <div class="card mt-3">
        <div class="card-body">
            <h5 class="card-title"><a href="/question/detail/{{ post.id }}">{{ post.title }}</a></h5>
            <h6 class="card-subtitle mb-2 text-muted">
                <i class="fas fa-caret-up"></i> {{post.NumberOfLike}}
                <i class="fas fa-caret-down"></i> {{post.NumberOfDislike}}
                <i class="far fa-comment"></i> {{post.comment_count}}
            </h6>
        </div>
        <div class="card-footer text-muted border-top-0">
            <p class="m-0"><i class="fas fa-user"></i> <a href="/profile/detail/{{post.author}}">{{post.author}}</a></p>
            <p class="m-0"><i class="fas fa-calendar-alt"></i> {{post.createdAt|date:"d/m/Y"}}</p>
        </div>
    </div>
    </div>
    {% empty %}
    <p><i>Người dùng chưa đăng.</i></p>
    {% endfor %}
  </div>
{% endblock %}

{% block sidebar %}
{% if user.is_authenticated and is_own_profile == True %}
<div class="card mt-3 bold">
  <div class="card-body shadow">
      <h5 class="card-title"><i class="fas fa-info-circle"></i> Quản Lí Tài Khoản</h5>
      <div class="list-group">
            <a class="list-group-item list-group-item-action" style="color: #007bff !important" href="/profile/change">Chỉnh sửa hồ sơ</a>
            <a class="list-group-item list-group-item-action" style="color: #007bff !important" href="/profile/claimrank">Nhận thứ hạng</a>
      </div>
  </div>
</div>
{% endif %}
{% endblock %}

Profile/templates/profile/ProfileChange.html
{% extends "base.html" %}

{% block title %}Chỉnh Sửa Hồ Sơ{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="mb-3">
        <h4 class="mb-3">Chỉnh sửa hồ sơ</h4>
        <div class="ml-3">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success">Lưu</button>
            </form>
        </div>
    </div>
{% endblock %}

Profile/templates/profile/SearchProfile.html
{% extends "base.html" %}

{% block title %}Tìm Kiếm Hồ Sơ{% endblock %}
{% block nav-profile-drop %}active{% endblock %}
{% block nav-search-user %}active{% endblock %}

{% load static %}

{% block content %}
<!-- Search Form -->
<h3><i class="fas fa-search"></i> Tìm kiếm</h3>
<div>
    <form class="form-inline mb-3" method="get">
        <input required name="username" class="form-control mr-sm-2" type="search" placeholder="Username Người Dùng" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Tìm Kiếm</button>
    </form>
    <p>(Lưu ý nhỏ là Username không có chứa dấu cách " " và chỉ chứa các từ trong bảng chữ cái tiếng Anh)</p>
    {% if is_searching == True %}    
        <a href="/profile/search">Quay lại tìm kiếm</a> 
    {% endif %}
</div>

<!-- Display list -->
{% if is_searching == True %} 
<h3>Danh sách tìm thấy</h3>
<div class="card-deck">
    <div class="row">
        {% for user in usersFound %} 
        <div class="col-12">
            <div class="card mb-2">
                <div class="card-body">
                    <h5 class="card-title">Username: {{ user.username }}</h5>
                    <h5 class="card-title">Họ và tên: {{ user.last_name }} {{ user.first_name }}</h5>
                    <a href="/profile/detail/{{user.username}}" class="btn btn-primary btn-sm">Xem hồ sơ</a>
                </div>
            </div>
        </div>
        {% empty %} <h6 class="card-title">Không tìm thấy người dùng!</h6>
        {% endfor %}
    </div>
</div>
{% endif %}
{% endblock %}

Profile/templates/profile/claimRank.html
{% extends "base.html" %}

{% block title %}Hồ Sơ - Nhận Hạng{% endblock %}
{% block nav-profile-drop %}active{% endblock %}

{% block content %}
<div class="mb-3">
    <h4 class="mb-3">Nhận hạng của bạn</h4>
    {% if isClaimed == False %} 
        <div class="ml-3">
            <form method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-success">Claim</button>
            </form>
        </div>
    {% else %}
        <h6>{{rank|safe}}</h6>
        <p>Cảm ơn bạn đã đóng góp cho chúng tôi. Mong bạn <i>"keep it going"</i> nhé!</p>
    {% endif %}
</div>
{% endblock %}

Profile/templates/profile/setting.html
{% extends "base.html" %}

{% block title %}Về Trang Web{% endblock %}
{% load static %}
{% block content %}
<h3><i class="fas fa-cog"></i> Cài đặt</h3>
<div class="ml-3">
    <button class="btn btn-primary btn-sm mt-3" type="button" id="theme-toggle">Chuyển Theme</button>
</div>
{% endblock %}

Profile/templates/profile/tmp1.html
{% extends "base.html" %}

{% block title %}Hồ Sơ Của Tôi{% endblock %}
{% block nav-profile-drop %}active{% endblock %}
{% block nav-my-profile %}active{% endblock %}

{% block content %}
    <center><h3 class="mb-3 mt-3">Thông tin của <i>{{user.name}}</i></h3></center>
    <div class="row">
        <div class="col-sm-7 ml-5">
            <h3>Thông tin cá nhân</h3>
            <div class="ml-4">
                <h4>{{user.name}}</h4>
                <h5>@{{user.username}}</h5>
                <ul>
                    <li>vai trò: {{user.get_role_display}}</li>
                    <li>Tài khoản thành lập vào: {{user.createdAt|date:"d/m/Y"}}</li>
                </ul>
                <h5>about:</h5>
                <div class="ml-4">
                    {{user.about|linebreaks}}
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            {% if user.NumberOfPosts != 0 %}
                <h3>Các bài viết đã đăng:</h3>
                <table class="table table-sm table-hover table-bordered">
                    <thead>
                        <tr>
                            <td>Bài Viết</td>
                            <td></td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for post in posts %}
                            {% if post.is_verify == True %}
                                <tr>
                                    <td><a href="/hoctap/baiviet/{{post.post_id}}">{{post.title|capfirst}}</a></td>
                                    <td>{{post.createdAt|date:'d/m/Y'}}</td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}
        </div>
    </div>
{% endblock %}

Profile/templates/profile/topUsers.html
{% extends "base.html" %}

{% block title %}Thành Viên Tích Cực{% endblock %}
{% block nav-profile-drop %}active{% endblock %}
{% block nav-activemember %}active{% endblock %}

{% block content %}
<table class="table table-sm table-striped table-bordered table-hover">
    <h6>Top Thành Viên</h6>
    <thead>
        <tr>
            <td class="text-center" style="width: 5%">#</td>
            <td style="width: 30%">Tên truy cập</td>
            <td style="width: 55%">Họ và Tên</td>
            <td class="text-center" style="width: 10%">Số bài viết</td>
        </tr>
    </thead>
    <tbody>
        {% for member in topUsers %}
            <tr>
                <td class="text-center">{{ forloop.counter }}</td>
                <td>
                    <a href="/profile/detail/{{member.user}}">{{member.user}}</a>
                    {% if member.rank == 'A' %} 
                    <i class="fas fa-medal" style="color: gold"></i>
                    {% elif member.rank == 'B' %}
                    <i class="fas fa-medal" style="color: silver"></i>
                    {% elif member.rank == 'C' %} 
                    <i class="fas fa-medal" style="color: #cd7f32"></i>
                    {% endif %}
                </td>
                <td>{{member.name}}</a></td>
                <td class="text-center">{{member.NumberOfPosts}}</td>
            </tr>
        {% endfor %}  
    </tbody>
</table>
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if topUsers.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ topUsers.previous_page_number }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
        {% endif %}

        {% for page in topUsers.paginator.page_range %}
            {% if topUsers.number == page %}
                <li class="page-item active"><a class="page-link" href="#">{{ page }}</a></li>
            {% elif page > topUsers.number|add:'-3' and page < topUsers.number|add:'3' %}
                <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
            {% endif %}
        {% endfor %}

        {% if topUsers.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ topUsers.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
        {% endif %}
    </ul>
</nav>

{% endblock %}